name: 'coder-ka/env2dotenv'
description: 'Read environment variables and output to a file in dotenv format.'
author: 'coder-ka'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'file-plus'
  color: 'orange'

# Define your inputs here.
inputs:
  keys:
    description: 'comma separated environment variables to read'
    required: true
  output:
    description: 'output file path in dotenv format.'
    required: false
    default: '.env'

runs:
  using: node20
  main: dist/index.js
